# Generated by Django 4.2.7 on 2025-07-15 13:40

import ExpenseTracker.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('month', models.IntegerField(default=ExpenseTracker.models.current_month)),
                ('year', models.IntegerField(default=ExpenseTracker.models.current_year)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseTracker.register')),
            ],
            options={
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
